default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: appearance_development
  username: valya
  password: valya

test:
  <<: *default
  database: db_test
  username: valya
  password: valya

production:
  <<: *default
  database: db_production
